### ISSUE TITLE
Fehler bei der Installation

### ISSUE THREAD

**Issue by Toysman** [xsawa32/ioBroker.rika-firenet#19]
Hallo,

bei der Installation erhalte ich folgendes Fehler Log

host.raspberrypi | 2021-06-30 18:43:28.736 | info | iobroker exit 25
host.raspberrypi | 2021-06-30 18:43:27.705 | error | iobroker host.raspberrypi Cannot install "npm: 2
host.raspberrypi | 2021-06-30 18:43:27.699 | info | iobroker /bin/sh: 1: Syntax error: Unterminated quoted string
host.raspberrypi | 2021-06-30 18:43:27.673 | info | iobroker npm install "npm --loglevel error --prefix "/opt/iobroker" (System call)
host.raspberrypi | 2021-06-30 18:43:27.670 | info | iobroker NPM version: 6.14.12
host.raspberrypi | 2021-06-30 18:43:27.068 | info | iobroker install "npm
host.raspberrypi | 2021-06-30 18:43:25.228 | info | iobroker url "npm install iobroker.rika-firenet"

Bitte um Info bzw. Unterstützung... Danke !

**Comment by xsawa32** [comment]
Serwus Toysman.

mit deiner Fehlermeldung kann ich leider nichts anfangen.
Den Adapter bitte folgendermaßen installieren, da es kein offiziell veröffentlichter Adapter ist:

iobroker öffnen
zu Adapter wechseln
Button "installieren aus eigener URL" drücken
ganz oben auf "Beliebig" gehen
Bei "URL oder Dateipfad" folgendes eintragen: https://github.com/xsawa32/ioBroker.rika-firenet
Button installieren drücken

Wenn keine Instanz automatisch angelegt wird:
wieder in Adapter wechseln
Instanz von Rika-Firenet hinzufügen
Felder ausfüllen
Fertig

Hab das Ganze jetzt auf verschiedenen iobroker-Installationen ausprobiert, ohne Probleme:

=== raspberrypi-iobroker ===
Node.js
v12.22.2 (Es gibt eine neuere Version: v12.22.4)
NPM
6.14.13

=== Windows 10 ===
Node.js
v14.15.1 (Es gibt eine neuere Version: v14.17.4 - Empfohlene Version v12.22.4)
NPM
6.14.8
